### ISSUE TITLE
use ros controller, can't publish the motor's feedback torque topic

### ISSUE THREAD

**Issue by chenchunyue123** [cyberbotics/webots_ros#16]
if enable the motor's feedback, but can't publish topic!

**Comment by DavidMansolino** [comment]
Hi @chenchunyue123, can you provide a very simple example (world and node) that reproduce the issue?

**Comment by chenchunyue123** [comment]
OK,
you can open an a new world, add a new robot(I use the kuka youbot), then choose the ros controller.
rosservice call /youBot_8046_chunyu/arm2/torque_feedback_sensor/enable "value: 1" 
rosservice call /youBot_8046_chunyu/arm2/set_torque "value: 0.0" 

but has no the "/<device_name>/force_feedback" topic.
maybe you can try.

**Comment by DavidMansolino** [comment]
Ok thank you, we will try this and fix it if we can reproduce it as soon as possible.

**Comment by DavidMansolino** [comment]
I just tried and I can confirm I can reproduce the issue.
I will try to fix this.

**Comment by chenchunyue123** [comment]
Ok thank you, look forward to your good news.

**Comment by DavidMansolino** [comment]
The issue was fixed in cyberbotics/webots#1581, the issue was on the Webots controller side, you will be able to download a nightly release of Webots R2020a-revision2 including the patch from tomorrow morning here: https://github.com/cyberbotics/webots/releases
Do not hesitate to re-open the issue if this doesn't fix the problem.
