### ISSUE TITLE
RecognitionObject: the parameter "seq" is not continuous.

### ISSUE THREAD

**Issue by SEUZTh** [cyberbotics/webots_ros#64]
Hello, I used the function `from webots_ros.msg import RecognitionObject`.
The object information it returns is not enough. I found that the parameter "seq" is not continuous.
I am not sure if this is a bug. But I am sure that this is not because some messages were not received. Just cyclically publish the information of the two fixed items in a picture

In addition, this can't return the number of the objects. Perhaps this is due to the origin of a message that only contains information about one object.

Looking forward to your reply.

**Comment by stefaniapedrazzi** [comment]
Could you please share your code?
What do you refer to with the parameter "seq"?
This is not part of the `RecognitionObject` msg definition.

> In addition, this can't return the number of the objects. Perhaps this is due to the origin of a message that only contains information about one object.

Yes, the message only contains information about the current object.
The number of recognition objects should be published in a separate topic.

**Comment by stefaniapedrazzi** [comment]
> I found that the parameter "seq" is not continuous.

The `header.seq` value is handled completely by ROS and it is increased automatically.
So if the "seq" value is not continuous it means that some other messages including `std_msgs:Header`have been published meanwhile.

I'm also comparing the published recognized objects and the ones received by the subscriber and for me when the "header.seq" values are not consecutive it is because some of the recognized object messages are not received by the subscriber.

**Comment by stefaniapedrazzi** [comment]
Webots `ros` controller is publishing messages for all the recognized objects, but the subscribers only receive some of them.
I tried to inspect this issue but didn't find the cause of the issue yet.

I'm wondering if it would not be better to publish a single message per time steps including all the recognition objects instead of publishing multiple message per time steps (one for each recognized objects).
The message would be something like:
```
Header header
uint32 size
webots_ros/RecognitionObject[] objects
```
Not sure what is the ROS best practice in this case, but a single message would be more "safe": if received, the count of recognized objects is correct and there is not the risk to miss some recognized objects.

**Comment by evilmind1** [comment]
Hello webots team,
    Is there any temporary solution for this issue ?

**Comment by stefaniapedrazzi** [comment]
For the moment I could not find any workaround.
But if you need an immediate solution, you can modify and recompile yourself the `ros` controller and `webots_ros` package and publish a single message for all the recognized objects as suggested.

Otherwise we should be able to fix it by next Wednesday.

**Comment by epcm** [comment]
> For the moment I could not find any workaround. But if you need an immediate solution, you can modify and recompile yourself the `ros` controller and `webots_ros` package and publish a single message for all the recognized objects as suggested.
> 
> Otherwise we should be able to fix it by next Wednesday.

`RecognizationObjects` isn't available now according to https://github.com/cyberbotics/webots/issues/4127#issue-1107052391

**Comment by BenjaminHug8** [comment]
Solved by https://github.com/cyberbotics/webots/pull/4139.
